# Generated by Django 3.1.5 on 2021-05-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portafolio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Portafolio', 'verbose_name_plural': 'Portafolios'},
        ),
        migrations.AddField(
            model_name='portafolio',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Direccion web'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='image',
            field=models.ImageField(default='null', upload_to='images', verbose_name='imagen'),
        ),
    ]
